package com.example.service;


import com.example.pojo.SysUser;

import java.util.List;

public interface UserService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    int deleteByPrimaryKey(Object object);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    int insert(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    SysUser selectByPrimaryKey(Object id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    int updateByPrimaryKey(SysUser record);


    List<SysUser> queryStudentList(Object o);

    List<SysUser> queryStudentListPage(SysUser o, Integer pageIndex, Integer pageSize);

    public SysUser queryUserSimplyInfoById(String id);
}