package com.example.service.impl;
/*
 * @author 瞿亮
 * @description //TODO $
 * @date $ $
 **/

import com.example.mapper.StudentMapper;
import com.example.pojo.Student;
import com.example.service.StudentService;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class StudentServiceImpl implements StudentService {


    @Autowired
    private StudentMapper studentMapper;


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @param id
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    @Override
    public int deleteByPrimaryKey(Integer id) {
        return studentMapper.deleteByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @param record
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    @Override
    public int insert(Student record) {
        return studentMapper.insert(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @param record
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    @Override
    public int insertSelective(Student record) {
        return studentMapper.insertSelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @param id
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    @Override
    public Student selectByPrimaryKey(Integer id) {
        return studentMapper.selectByPrimaryKey(id);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @param record
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    @Override
    public int updateByPrimaryKeySelective(Student record) {
        return studentMapper.updateByPrimaryKeySelective(record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @param record
     * @mbggenerated Sat Aug 25 01:12:38 CST 2018
     */
    @Override
    public int updateByPrimaryKey(Student record) {
        return studentMapper.updateByPrimaryKey(record);
    }

    @Override
    public List<Student> queryStudentList(Student student) {
        return studentMapper.selectByExample(student);
    }
}